# Generated by Django 4.0.1 on 2022-07-19 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('idEmpleado', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Empleado')),
                ('nombre', models.CharField(blank=True, max_length=150, null=True)),
                ('apellido', models.CharField(blank=True, max_length=150, null=True)),
                ('correo', models.EmailField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
