# Generated by Django 4.0.1 on 2022-07-19 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_empleados_delete_empleado'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Empleados',
            new_name='Empleado',
        ),
        migrations.AlterModelOptions(
            name='empleado',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='empleado',
            table='empleado',
        ),
    ]
