# Generated by Django 4.0.1 on 2022-07-20 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_rename_empleados_empleado_alter_empleado_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='correo',
            field=models.IntegerField(blank=True, max_length=45, null=True),
        ),
    ]
