# Generated by Django 4.0.1 on 2022-07-20 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_alter_empleado_correo'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='telefono',
            field=models.IntegerField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='correo',
            field=models.EmailField(blank=True, max_length=150, null=True),
        ),
    ]
