# Generated by Django 4.0.1 on 2022-07-20 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_empleado_telefono_alter_empleado_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='correo',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='telefono',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
