# Generated by Django 4.0.1 on 2022-07-26 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0007_bandera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bandera',
            name='valor',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
